language: python
python:
  - "3.6.3"

#Django & Database
addons:
  postgresql: "10.1"

sudo: false

env:
  -DJANGO=1.10 DB=mysql
  -DJANGO=1.10 DB=sqlite3
  -DJANGO=1.10 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls


#mysql db creation
before_script:
  - sleep 15
  - psql -c 'create database test;' -U postgres

# command to run tests
script:
  - python test_runner.py test
  - coverage run --source=django_blog_it.posts,django_blog_it.django_blog_it test_runner.py test

after_success:
  coveralls
