language: python
python:
  - "3.4"

#Django & Database
addons:
  postgresql: "9.4"

sudo: false

env:
  -DJANGO=1.9 DB=mysql
  -DJANGO=1.9 DB=sqlite3
  -DJANGO=1.9 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install mysql-python --use-mirrors

#mysql db creation
before_script:
  - sleep 15
  - psql -c 'create database test;' -U postgres

# command to run tests
script:
  - python manage.py test
  - coverage run --source=micro_blog.posts,micro_blog.microblog manage.py test

after_success:
  coveralls
